import type { Locale } from "./types";

export const copy = {
  roleGate: {
    title: { en: "Welcome to PostUp+", es: "Bienvenido a PostUp+" },
    subtitle: {
      en: "Choose how you're using the app today.",
      es: "Elija cómo usará la aplicación hoy.",
    },
    patient: { en: "I'm a patient", es: "Soy paciente" },
    patientDesc: {
      en: "Recovery dashboard, pain check-ins, medications",
      es: "Panel de recuperación, dolor, medicamentos",
    },
    provider: { en: "I'm a provider", es: "Soy proveedor" },
    providerDesc: {
      en: "Clinic view — patient list, alerts, care team tools",
      es: "Vista clínica — lista de pacientes, alertas, herramientas",
    },
  },
  patientPick: {
    title: { en: "Choose a demo patient", es: "Elija un paciente demo" },
    subtitle: {
      en: "Skip sign-in — pick a chart to open the recovery dashboard.",
      es: "Sin inicio de sesión — elija un expediente para abrir el panel.",
    },
    continue: { en: "Open dashboard", es: "Abrir panel" },
    dayPostOp: { en: "Day", es: "Día" },
    postOp: { en: "post-op", es: "postoperatorio" },
  },
  login: {
    title: { en: "Sign in", es: "Iniciar sesión" },
    subtitle: {
      en: "Use your clinic username and password.",
      es: "Use su usuario y contraseña de la clínica.",
    },
    username: { en: "Username", es: "Usuario" },
    password: { en: "Password", es: "Contraseña" },
    submit: { en: "Sign in", es: "Iniciar sesión" },
    error: {
      en: "Invalid username or password for this role.",
      es: "Usuario o contraseña incorrectos para este rol.",
    },
  },
  loading: {
    title: { en: "Loading your chart", es: "Cargando su expediente" },
    steps: {
      en: [
        "Verifying identity…",
        "Loading surgery history…",
        "Pulling prescriptions…",
        "Preparing your care plan…",
      ],
      es: [
        "Verificando identidad…",
        "Cargando historial quirúrgico…",
        "Obteniendo recetas…",
        "Preparando su plan de cuidado…",
      ],
    },
  },
  dashboard: {
    chatTitle: { en: "Talk to your care team", es: "Hable con su equipo de cuidado" },
    chatSubtitle: {
      en: "Ask about hip pain, walker use, precautions, or meds — answers match your THA chart.",
      es: "Pregunte sobre dolor de cadera, andador, precauciones o medicamentos — según su expediente THA.",
    },
    chatPlaceholder: {
      en: "Ask a question about your recovery…",
      es: "Haga una pregunta sobre su recuperación…",
    },
    send: { en: "Send", es: "Enviar" },
    dayPostOp: { en: "Day", es: "Día" },
    postOp: { en: "post-op", es: "postoperatorio" },
    moveTitle: { en: "Move a little, often", es: "Muévase un poco, con frecuencia" },
    moveBody: {
      en: "Short walks with your walker — 5 minutes, often — help your new hip heal and reduce stiffness.",
      es: "Caminatas cortas con el andador — 5 minutos, con frecuencia — ayudan a sanar la cadera nueva y reducen rigidez.",
    },
    nextWalk: { en: "Next walk due in", es: "Próxima caminata en" },
    walkNow: { en: "Time for a 5‑min walk now!", es: "¡Hora de caminar 5 min!" },
    logWalk: { en: "Log walk", es: "Registrar" },
    walkLogged: { en: "Walk logged — next in ~60 min", es: "Caminata registrada — próxima en ~60 min" },
    painTitle: {
      en: "How does your new hip feel?",
      es: "¿Cómo se siente su cadera nueva?",
    },
    painHint: {
      en: "Rate hip, groin, thigh, or buttock pain after your total hip replacement — 1 is calm, 10 needs urgent care.",
      es: "Califique dolor en cadera, ingle, muslo o glúteo tras el reemplazo total — 1 es tranquilo, 10 requiere atención urgente.",
    },
    sliderMin: {
      en: "Hip calm",
      es: "Cadera tranquila",
    },
    sliderMax: { en: "Call clinic", es: "Llame a la clínica" },
    functionalToggle: {
      en: "＋ What can you do right now?",
      es: "＋ ¿Qué puede hacer ahora?",
    },
    functionalHide: {
      en: "− Hide functional check",
      es: "− Ocultar chequeo funcional",
    },
    functionalTitle: { en: "Functional check", es: "Chequeo funcional" },
    savePain: { en: "Save pain check-in", es: "Guardar dolor" },
    movementTitle: { en: "Today's movement", es: "Movimiento de hoy" },
    movementSub: {
      en: "5-min walks, often — tap + when you move",
      es: "Caminatas de 5 min — toque + al moverse",
    },
    walks: { en: "Walks", es: "Caminatas" },
    minTotal: { en: "min total · goal ~8 walks", es: "min total · meta ~8 caminatas" },
    medsTitle: { en: "Your medications", es: "Sus medicamentos" },
    takeWithFood: { en: "Take with food", es: "Tomar con comida" },
    takeWithFoodDesc: {
      en: "Always take each dose with a meal or snack to reduce nausea.",
      es: "Tome cada dosis con comida o un refrigerio para reducir náuseas.",
    },
    every6h: { en: "Every 6 hours", es: "Cada 6 horas" },
    every6hDesc: {
      en: "Do not take more often. Keep doses spaced apart.",
      es: "No tome con más frecuencia. Mantenga las dosis separadas.",
    },
    btnWithFood: { en: "I took it with food", es: "Lo tomé con comida" },
    btnWithFoodSub: {
      en: "Tap when you dose with a meal or snack",
      es: "Toque al tomar con comida",
    },
    btnDose: { en: "Mark dose taken", es: "Marcar dosis tomada" },
    btnDoseSub: {
      en: "Every 6 hours — logs your schedule",
      es: "Cada 6 horas — registra su horario",
    },
    nextDose: { en: "Next dose due in", es: "Próxima dosis en" },
    rememberFood: { en: "remember food", es: "recuerde comida" },
    allFaqs: { en: "All FAQs", es: "Todas las preguntas" },
    faqDesc: { en: "Common questions", es: "Preguntas frecuentes" },
    quickAnswers: { en: "Quick answers", es: "Respuestas rápidas" },
    faqModalTitle: { en: "Frequently asked questions", es: "Preguntas frecuentes" },
    faqModalHint: { en: "Tap a question to expand.", es: "Toque una pregunta para expandir." },
    close: { en: "Close", es: "Cerrar" },
    yes: { en: "Yes", es: "Sí" },
    help: { en: "Help", es: "Ayuda" },
    no: { en: "No", es: "No" },
  },
  provider: {
    pageTitle: { en: "Patient chart", es: "Expediente del paciente" },
    bannerProcedure: { en: "Procedure", es: "Procedimiento" },
    bannerSurgeon: { en: "Surgeon", es: "Cirujano" },
    bannerAllergies: { en: "Allergies", es: "Alergias" },
    bannerLang: { en: "Language", es: "Idioma" },
    bannerPhone: { en: "Phone", es: "Teléfono" },
    bannerMrn: { en: "MRN", es: "MRN" },
    bannerLastSync: { en: "Last sync", es: "Última sincronización" },
    bannerPod: { en: "POD", es: "POD" },
    bannerPodLong: { en: "Day post-op", es: "Día post-operatorio" },
    bannerToday: { en: "today", es: "hoy" },
    bannerPodProgress: { en: "Recovery timeline", es: "Línea de recuperación" },
    signalsTitle: { en: "Signals", es: "Señales" },
    signalsActive: { en: "active", es: "activas" },
    signalsEmpty: { en: "All signals clear", es: "Sin señales activas" },
    signalsMore: { en: "more informational signals", es: "señales informativas más" },
    severityCritical: { en: "Critical", es: "Crítico" },
    severityWarn: { en: "Warning", es: "Advertencia" },
    severityInfo: { en: "Info", es: "Info" },
    painTitle: { en: "Pain over time", es: "Dolor en el tiempo" },
    painRange3d: { en: "3d", es: "3d" },
    painRange7d: { en: "7d", es: "7d" },
    painRangeAll: { en: "All", es: "Todo" },
    painAxisY: { en: "Pain (0–10)", es: "Dolor (0–10)" },
    painAxisX: { en: "Post-op day", es: "Día post-op" },
    painLegendDose: { en: "Dose taken", es: "Dosis tomada" },
    painLegendSkipped: { en: "Dose skipped", es: "Dosis omitida" },
    painLegendPlateau: { en: "Plateau region", es: "Región de meseta" },
    movementTitle: { en: "Movement adherence", es: "Adherencia al movimiento" },
    movementSubtitle: {
      en: "last 7 days · goal 8 walks/day",
      es: "últimos 7 días · meta 8 caminatas/día",
    },
    movementWalks: { en: "walks", es: "caminatas" },
    movementProjected: { en: "projected", es: "proyectado" },
    movementToday: { en: "Today's pacing", es: "Ritmo de hoy" },
    movementHourLabel: { en: "Time of day", es: "Hora del día" },
    rxTitle: { en: "AI recommendations", es: "Recomendaciones de la IA" },
    rxSubtitle: {
      en: "Derived from chart signals — review evidence before adding.",
      es: "Derivado de las señales — revise la evidencia antes de agregar.",
    },
    rxAdd: { en: "Add to plan", es: "Agregar al plan" },
    rxAdded: { en: "Added", es: "Agregado" },
    rxWhy: { en: "Why?", es: "¿Por qué?" },
    rxHide: { en: "Hide rationale", es: "Ocultar" },
    rxKindAdjunct: { en: "Adjunct", es: "Adyuvante" },
    rxKindPrimary: { en: "Primary", es: "Primario" },
    rxKindTaper: { en: "Taper plan", es: "Plan de descenso" },
    rxKindNonPharm: { en: "Non-pharmacologic", es: "No farmacológico" },
    rxEmpty: {
      en: "No recommendations from current signals.",
      es: "Sin recomendaciones para las señales actuales.",
    },
    rxServiceWarming: {
      en: "AI service warming up — try again in a moment.",
      es: "Servicio de IA iniciando — intente de nuevo en un momento.",
    },
    evidenceTitle: { en: "Evidence search", es: "Búsqueda de evidencia" },
    evidenceHint: {
      en: "Ask about pain pharmacology — chart context is auto-attached.",
      es: "Pregunte sobre farmacología — el contexto del expediente se adjunta.",
    },
    evidencePlaceholder: {
      en: "e.g., first-line adjunct for plateaued post-ACL pain at POD 7",
      es: "p. ej., adyuvante de primera línea para meseta post-ACL en POD 7",
    },
    evidenceSearch: { en: "Search", es: "Buscar" },
    evidenceSearching: {
      en: "Searching evidence sources…",
      es: "Buscando fuentes…",
    },
    evidenceSources: { en: "Sources", es: "Fuentes" },
    evidenceSuggested: { en: "Suggested", es: "Sugeridas" },
    evidenceServiceWarming: {
      en: "Evidence service warming up — try again in a moment.",
      es: "Servicio de evidencia iniciando — intente de nuevo.",
    },
    planTitle: { en: "Proposed plan", es: "Plan propuesto" },
    planSubtitle: {
      en: "Items added this session.",
      es: "Elementos agregados en esta sesión.",
    },
    planEmpty: {
      en: "No plan items yet — add a recommendation above.",
      es: "Aún sin elementos — agregue una recomendación arriba.",
    },
    planRemove: { en: "Remove", es: "Quitar" },
    planReason: { en: "from", es: "de" },
    planFinalize: {
      en: "Finalize & notify patient",
      es: "Finalizar y notificar al paciente",
    },
    planFinalized: {
      en: "Plan saved · patient will see updates on next sync",
      es: "Plan guardado · el paciente lo verá en la próxima sincronización",
    },
    tabChart: { en: "Chart", es: "Expediente" },
    tabSummary: { en: "Pain summary", es: "Resumen de dolor" },
    summarySubtitle: {
      en: "AI-condensed insights from the patient’s chat history.",
      es: "Resumen de IA del historial de chat del paciente.",
    },
    summaryRefresh: { en: "Regenerate", es: "Regenerar" },
    summaryRegenerating: { en: "Regenerating…", es: "Regenerando…" },
    summaryEmptyTitle: { en: "No chat yet", es: "Sin chat todavía" },
    summaryEmptyBody: {
      en: "Insights will appear once the patient messages the care team.",
      es: "Las ideas aparecerán cuando el paciente envíe mensajes.",
    },
    summaryLoading: {
      en: "Reading chat history…",
      es: "Leyendo historial de chat…",
    },
    summaryError: {
      en: "Couldn’t generate insights — try again.",
      es: "No se pudieron generar ideas — intente de nuevo.",
    },
    summaryBasedOn: { en: "Based on", es: "Basado en" },
    summaryTurns: { en: "messages", es: "mensajes" },
    summaryNarrative: { en: "How they're doing", es: "Cómo están" },
    summaryPainPattern: { en: "Pain pattern", es: "Patrón de dolor" },
    summaryTriggers: { en: "Triggers", es: "Desencadenantes" },
    summaryRelievers: { en: "What helps", es: "Lo que ayuda" },
    summarySentimentTitle: { en: "Sentiment trend", es: "Tendencia de ánimo" },
    summaryMoodTitle: { en: "Mood across chat", es: "Estado de ánimo" },
    summaryQuotesTitle: { en: "Key quotes", es: "Citas clave" },
    summaryConcernsTitle: { en: "Flagged concerns", es: "Preocupaciones marcadas" },
    summaryAdherenceTitle: { en: "Adherence observations", es: "Adherencia observada" },
    summaryNextVisitTitle: {
      en: "For next visit",
      es: "Para la próxima visita",
    },
    summaryOverallLabel: {
      en: "Overall sentiment",
      es: "Sentimiento general",
    },
  },
} as const;

export function t<T extends Record<Locale, string>>(
  block: T,
  locale: Locale,
): string {
  return block[locale];
}
